spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:32312/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dPixtBzOsXHjKgQTdIttxaRohoDHOKFX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
RECAPTCHA_SECRET_KEY=6LeVic4sAAAAAAPL6BxU5ECzF8lN-l3vVoApVB_l
